### PR TITLE
Fix unknown type name ssize_t

### PR DESCRIPTION
**Pull request by zaxbbun**

### CODE REVIEW

**Comment by tzvetkoff** [comment]
Thank you!
But from the GLibC manpages I see `ssize_t` is defined in `sys/types.h`.
I'll look this up a bit more and find the proper way to fix this (which might turn to be `unistd.h` nevertheless, since it includes quite a lot of stuff (but is, unfortunately, not portable.))

**Comment by tzvetkoff** [comment]
Can you share more info on what platform you are getting this error?

**Comment by zaxbbun** [comment]
- this is compile error

```
#11 66.41 error: dep/hashids.c/src/hashids.c: In function 'hashids_shuffle':
#11 66.41 dep/hashids.c/src/hashids.c:113:5: error: unknown type name 'ssize_t'
#11 66.41      ssize_t i;#11 66.41 error: dep/hashids.c/src/hashids.c: In function 'hashids_shuffle':
#11 66.41 dep/hashids.c/src/hashids.c:113:5: error: unknown type name 'ssize_t'
#11 66.41      ssize_t i;
```

```
[ci@devops-650fbfa22a76 /]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```
[ci@devops-650fbfa22a76 /]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)
```

- this is from **man ssize_t**
```
       ssize_t
              Include: <sys/types.h>.   Alternatively,  <aio.h>,  <monetary.h>,  <mqueue.h>,  <stdio.h>,
              <sys/msg.h>, <sys/socket.h>, <sys/uio.h>, or <unistd.h>.

              Used  for  a  count  of  bytes  or an error indication.  According to POSIX, it shall be a
              signed integer type capable of storing values at least in the range [-1,  SSIZE_MAX],  and
              the  implementation  shall support one or more programming environments where the width of
              ssize_t is no greater than the width of the type long.

              Glibc and most other implementations  provide  a  length  modifier  for  ssize_t  for  the
              printf(3) and the scanf(3) families of functions, which is z; resulting commonly in %zd or
              %zi for printing ssize_t values.  Although z works for ssize_t  on  most  implementations,
              portable POSIX programs should avoid using it—for example, by converting the value to int‐
              max_t and using its length modifier (j).

              Conforming to: POSIX.1-2001 and later.

              See also: read(2), readlink(2), readv(2), recv(2), send(2), write(2)

              See also the ptrdiff_t and size_t types in this page.

```

we should include one of the above header files in hashids

**Comment by zaxbbun** [comment]
> Thank you! But from the GLibC manpages I see `ssize_t` is defined in `sys/types.h`. I'll look this up a bit more and find the proper way to fix this (which might turn to be `unistd.h` nevertheless, since it includes quite a lot of stuff (but is, unfortunately, not portable.))

yes, ```ssize_t``` is defined in ```sys/types.h```, but ```sys/types.h``` dose not been included in hashids.c

**Comment by tzvetkoff** [comment]
Well, I've confirmed `ssize_t` is not actually needed, so no need to include additional headers.
A simple change to `size_t` is more than enough.
Latest changes in `master`, I'll also tag `v1.2.2`.

**Comment by zaxbbun** [comment]
thx

**Pull request closed without merging**
