### PR TITLE
Added a failing test case for hashids_encode

### PR DESCRIPTION
**Pull request by thedrow**
It seems like we're shuffling incorrectly somehow.
I'm not sure what's the cause of the issue though.

### CODE REVIEW

**Comment by tzvetkoff** [comment]
If we have a failing case `./src/test` will return 1, which will break `make check`.

**Comment by thedrow** [comment]
This PR is just to raise the issue. I have debugged this but I haven't found the problem yet.
Please reopen.

**Comment by tzvetkoff** [comment]
OK, I see your point but... Your PR seems to be wrong.

Here are the results from the JS version (which I consider "reference")

``` js
> new Hashids("ab'", 0, "cadjgbenkflqihmo").encode(5)
'qb'
> new Hashids("", 0, "dbomlfeagjkhcinp").encode(5)
'ab'
> new Hashids("", 0, "nb)1NCjag:?Fcs`H").encode(5555)
'abbbb'
```

And here's v1.1.0 CLI:

```
$ ./src/hashids -s "ab'" -l 0 -a "cadjgbenkflqihmo" 5
qb
$ ./src/hashids -s "" -l 0 -a "dbomlfeagjkhcinp" 5
ab
$ ./src/hashids -s "" -l 0 -a "nb)1NCjag:?Fcs\`H" 5555
abbbb
```

**Comment by thedrow** [comment]
Let me check the python version again. I'll get back to you on that.

**Pull request closed without merging**
